version: '2.1'

executors:
  main:
    docker:
      - image: cimg/go:1.17
      - image: redislabs/rebloom:latest
        command: redis-server --loadmodule /usr/lib/redis/modules/redisbloom.so --protected-mode no

jobs:

  # `test` tests the source code.
  test:
    executor: main
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: make test

  build:
    executor: main
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: make bin/safelock
      - run: bin/safelock --help

workflows:
  version: 2
  main:
    jobs:
      - test

      - build:
          requires:
            - test
